@baseUrl = http://localhost:8080
@contentType = application/json

### create a new user
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
    "name": "iDesoft Systems",
    "username": "idesoftd"
}

### read all users with limits
GET {{baseUrl}}/users?page=0&page_size=3
Content-Type: {{contentType}}

### read one user
GET {{baseUrl}}/users/1
Content-Type: {{contentType}}

### update user
PUT {{baseUrl}}/users/1
Content-Type: {{contentType}}

{
    "username": "idesoftbot",
    "disabled": true
}

### delete user
DELETE {{baseUrl}}/users/1
Content-Type: {{contentType}}
